import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import { Providers } from "./Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ideal Pancake",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="font-sans">
      <body className={inter.className}>
        <div className="bg-[#1b2838] text-white">
        <Providers>          
            <Navbar />
            {children}
        </Providers>
        </div>
      </body>
    </html>
  );
}

